# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5edc1ad8303cd6066687f354d22ecd19894f040e24497647d84ffb095a5c0abc3726073fd58fe3bd982247374106efb93bc33ccdc794d9fbace05eaafac7ad0b

test:
  secret_key_base: 5262024afb1ad8c3d5881aa8e567e2815d17ceb687a970dbfae8f6740f06fbbeaf109bf0b8d85eabd48d2fedc06500b5a4404592c5d6e8369ac995ba00e61a44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
